rest-proxy:
  image: confluentinc/cp-kafka-rest:7.2.1
  depends_on:
    - kafka
  environment:
    KAFKA_REST_HOST_NAME: rest-proxy
    KAFKA_REST_LISTENERS: http://0.0.0.0:8082
    KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
  ports:
    - '8082:8082'
